name: data-visualization-agent
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.11.9
 - langchain=0.1.16
 - langchain-openai<0.1
 - langchain-experimental=0.0.57
 - matplotlib=3.8.4
 - seaborn=0.13.2
 - tabulate
 - python-dotenv
 - pip